/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pneumonia.diagnosis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhaimenur
 */
public class Diagnosis_main extends javax.swing.JFrame {

    /**
     * Creates new form Diagnosis_main
     */
    public ResultSet rs;
    public Statement st;
    public Connection con;
     private PreparedStatement pst;
    double fever_1=0.1,fever_2=0.2,fever_3=0.3,
            cough_1=0.1,cough_2=0.2,cough_3=0.3,
            HR_1=0.1,HR_2=0.2,HR_3=0.3,
            RR_1=0.1,RR_2=0.2,RR_3=0.3,
            breathe_1=0.3,breathe_2=0.3,breathe_3=0.2,
            chest_1=0.1,chest_2=0.2,chest_3=0.3,
            appetite_1=0.1,appetite_2=0.2,appetite_3=0.3,
            chill_1=0.1,chill_2=0.2,chill_3=0.3;
    double total=0.0,result,tag=0;
    double fever_num, cough_num,HR_num,RR_num,breathe_num,chest_num,appetite_num,chill_num;
    public String ids;
    String patient_ids;
    int updateTag = 0;
    public Diagnosis_main() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
         //jRadioButton2.setSelected(true);
        Connection();
       
       
    }
    



public void Connection(){
    try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pneumonia", "root", "");
            st = con.createStatement();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fever1 = new javax.swing.JRadioButton();
        fever2 = new javax.swing.JRadioButton();
        fever3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cough1 = new javax.swing.JRadioButton();
        cough2 = new javax.swing.JRadioButton();
        cough3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        HR1 = new javax.swing.JRadioButton();
        HR2 = new javax.swing.JRadioButton();
        HR3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        RR1 = new javax.swing.JRadioButton();
        RR2 = new javax.swing.JRadioButton();
        RR3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Breath1 = new javax.swing.JRadioButton();
        Breathe2 = new javax.swing.JRadioButton();
        Breathe3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Chest1 = new javax.swing.JRadioButton();
        Chest2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Appetite1 = new javax.swing.JRadioButton();
        Appetite2 = new javax.swing.JRadioButton();
        diagnosis = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        previous_result = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pa_id = new javax.swing.JLabel();
        chest3 = new javax.swing.JRadioButton();
        appetite3 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        chill1 = new javax.swing.JRadioButton();
        chill2 = new javax.swing.JRadioButton();
        chill3 = new javax.swing.JRadioButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("jRadioButtonMenuItem4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("jRadioButtonMenuItem5");

        jRadioButton6.setText("jRadioButton6");

        jRadioButton17.setText("jRadioButton17");

        jRadioButton21.setText("jRadioButton21");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diagonosis Information");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Enter Patient Information");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("       Fever  :");

        fever1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        fever1.setText("97 - 99.6");
        fever1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fever1ActionPerformed(evt);
            }
        });

        fever2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        fever2.setText("99.7 - 100.4");
        fever2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fever2ActionPerformed(evt);
            }
        });

        fever3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        fever3.setText("100.5 <=");
        fever3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fever3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("     Cough  :");

        cough1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cough1.setText("2-3 days");
        cough1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cough1ActionPerformed(evt);
            }
        });

        cough2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cough2.setText("one weak");
        cough2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cough2ActionPerformed(evt);
            }
        });

        cough3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cough3.setText("one weak <");
        cough3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cough3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Heartbeat rate(H/R) :");

        HR1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        HR1.setText("mild");
        HR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HR1ActionPerformed(evt);
            }
        });

        HR2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        HR2.setText("moderate");
        HR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HR2ActionPerformed(evt);
            }
        });

        HR3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        HR3.setText("severe");
        HR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HR3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Respiratory rate(R/R)  :");

        RR1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RR1.setText("mild");
        RR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RR1ActionPerformed(evt);
            }
        });

        RR2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RR2.setText("moderate");
        RR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RR2ActionPerformed(evt);
            }
        });

        RR3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RR3.setText("severe");
        RR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RR3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("              Breatheing  :");

        Breath1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Breath1.setText("rapid breatheing");
        Breath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Breath1ActionPerformed(evt);
            }
        });

        Breathe2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Breathe2.setText("difficulty in breatheing");
        Breathe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Breathe2ActionPerformed(evt);
            }
        });

        Breathe3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Breathe3.setText("shortness of breatheing");
        Breathe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Breathe3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("         Chest pain   :");

        Chest1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Chest1.setText("mild");
        Chest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chest1ActionPerformed(evt);
            }
        });

        Chest2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Chest2.setText("moderate");
        Chest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chest2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("    Loss of appetite  :");

        Appetite1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Appetite1.setText("mild");
        Appetite1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Appetite1ActionPerformed(evt);
            }
        });

        Appetite2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Appetite2.setText("moderate");
        Appetite2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Appetite2ActionPerformed(evt);
            }
        });

        diagnosis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        diagnosis.setText("Diagnosis");
        diagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Previous Result :");

        previous_result.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        previous_result.setText("New Patient");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Patient  ID");

        pa_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        chest3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chest3.setText("severe");

        appetite3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        appetite3.setText("severe");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("    Shaking chills :");

        chill1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chill1.setText("mild");

        chill2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chill2.setText("moderate");

        chill3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        chill3.setText("severe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pa_id, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Breath1)
                                    .addComponent(Chest1)
                                    .addComponent(Appetite1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel5))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fever1)
                                    .addComponent(cough1)
                                    .addComponent(HR1)
                                    .addComponent(RR1)
                                    .addComponent(chill1)
                                    .addComponent(diagnosis))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Breathe2)
                                            .addComponent(RR2)
                                            .addComponent(HR2)
                                            .addComponent(cough2)
                                            .addComponent(fever2)
                                            .addComponent(Chest2)
                                            .addComponent(Appetite2)
                                            .addComponent(chill2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chill3)
                                            .addComponent(RR3)
                                            .addComponent(Breathe3)
                                            .addComponent(HR3)
                                            .addComponent(fever3)
                                            .addComponent(cough3)
                                            .addComponent(chest3)
                                            .addComponent(appetite3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(previous_result, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(pa_id)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fever1)
                    .addComponent(fever2)
                    .addComponent(fever3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cough1)
                        .addComponent(cough2)
                        .addComponent(cough3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(HR1)
                    .addComponent(HR2)
                    .addComponent(HR3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RR1)
                    .addComponent(RR2)
                    .addComponent(RR3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Breath1)
                    .addComponent(Breathe2)
                    .addComponent(Breathe3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Chest1)
                    .addComponent(Chest2)
                    .addComponent(chest3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Appetite1)
                    .addComponent(Appetite2)
                    .addComponent(appetite3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chill2)
                            .addComponent(chill1)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chill3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(diagnosis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(previous_result, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void update(String lastName) 
{
    try {
            updateTag=1;
            String sql12 = "select * from diagnosis_info where ID= '" + lastName + "' ";
            rs = st.executeQuery(sql12);
            while (rs.next()) {
                String id = rs.getString("ID");
                pa_id.setText(id);
                String f = rs.getString("fever");
                double num = Double.parseDouble(f);
                if(num==0.1)
                fever1.setSelected(true);
                else if(num == 0.2)
                 fever2.setSelected(true);
                else if(num == 0.3)
                 fever3.setSelected(true);
                
                 String c = rs.getString("cough");
                double num1 = Double.parseDouble(c);
                if(num1==0.1)
                cough1.setSelected(true);
                else if(num1 == 0.2)
                 cough2.setSelected(true);
                else if(num1 == 0.3)
                 cough3.setSelected(true);
                
                 String H = rs.getString("heartbeat");
                double num2 = Double.parseDouble(H);
                if(num2 == 0.1)
                HR1.setSelected(true);
                else if(num2 == 0.2)
                 HR2.setSelected(true);
                else if(num2 == 0.3)
                 HR3.setSelected(true);
                
                 String R = rs.getString("respiratory");
                double num3 = Double.parseDouble(R);
                if(num3 == 0.1)
                RR1.setSelected(true);
                else if(num3 == 0.2)
                 RR2.setSelected(true);
                else if(num3 == 0.3)
                 RR3.setSelected(true);
                
                String breathe = rs.getString("breatheing");
                double num4 = Double.parseDouble(breathe);
                if(num4 == 0.3)
                Breathe2.setSelected(true);
                else if(num4 == 0.2)
                 Breathe3.setSelected(true);
                
                String chest = rs.getString("chest_pain");
                double num5 = Double.parseDouble(chest);
                if(num5 == 0.1)
                Chest1.setSelected(true);
                else if(num5 == 0.2)
                Chest2.setSelected(true);
                else if(num5 == 0.3)
                chest3.setSelected(true);
                
                String appetite = rs.getString("loss_of_appetite");
                double num6 = Double.parseDouble(appetite);
                if(num6 == 0.1)
                Appetite1.setSelected(true);
                else if(num6 == 0.2)
                Appetite2.setSelected(true);
                else if(num6 == 0.3)
                appetite3.setSelected(true);
                
                String results = rs.getString("Result");
                double num7 = Double.parseDouble(results);
                if(num7>0.0 && num7<=0.13)
                previous_result.setText("Mild( "+results+" )");
                else if(num7>0.13 && num7<=0.23)
                 previous_result.setText("Moderate( "+results+" )");
                else if(num7>0.23 && num7<=0.3)
                 previous_result.setText("Severe( "+results+" )");
                
                String chills = rs.getString("shaking_chill");
                double num8 = Double.parseDouble(chills);
                if(num8 == 0.1)
                Appetite1.setSelected(true);
                else if(num8 == 0.2)
                Appetite2.setSelected(true);
                else if(num8 == 0.3)
                appetite3.setSelected(true);
                
            }
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Database Error");
        }
}

    
    private void diagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisActionPerformed
        try{
          if(fever1.isSelected())
          {
              total= total+fever_1;
              tag++;
              fever_num= fever_1;
          }
          if(fever2.isSelected())
          {
              total= total+fever_2;
              tag++;
              fever_num= fever_2;
          }
          if(fever3.isSelected())
          {
              total= total+fever_3;
              tag++;
              fever_num= fever_3;
          }
          if(cough1.isSelected())
          {
              total= total+cough_1;
              tag++;
              cough_num=cough_1;
          }
          if(cough2.isSelected())
          {
              total= total+cough_2;
              tag++;
              cough_num=cough_2;
          }
          if(cough3.isSelected())
          {
              total= total+cough_3;
              tag++;
              cough_num=cough_3;
          }
          if(HR1.isSelected())
          {
              total= total+HR_1;
              tag++;
              HR_num = HR_1;
          }
          if(HR2.isSelected())
          {
              total= total+HR_2;
              tag++;
              HR_num = HR_2;
          }
          if(HR3.isSelected())
          {
              total= total+HR_3;
              tag++;
              HR_num = HR_3;
          }
          
           if(RR1.isSelected())
          {
              total= total+RR_1;
              tag++;
              RR_num=RR_1;
          }
          if(RR2.isSelected())
          {
              total= total+RR_2;
              tag++;
              RR_num=RR_2;
          }
          if(RR3.isSelected())
          {
              total= total+RR_3;
              tag++;
              RR_num=RR_3;
          }
          
          if(Breath1.isSelected())
          {
              total= total+breathe_1;
              tag++;
              breathe_num=breathe_1;
          }
          if(Breathe2.isSelected())
          {
              total= total+breathe_2;
              tag++;
              breathe_num=breathe_2;
          }
          if(Breathe3.isSelected())
          {
              total= total+breathe_3;
              tag++;
              breathe_num=breathe_3;
          }
          
           if(Chest1.isSelected())
          {
              total= total+chest_1;
              tag++;
              chest_num=chest_1;
          }
          if(Chest2.isSelected())
          {
              total= total+chest_2;
              tag++;
              chest_num=chest_2;
          }
          if(chest3.isSelected())
          {
              total= total+chest_3;
              tag++;
              chest_num=chest_3;
          }
          
           if(Appetite1.isSelected())
          {
              total= total+appetite_1;
              tag++;
              appetite_num=appetite_1;
          }
          if(Appetite2.isSelected())
          {
              total= total+appetite_2;
              tag++;
               appetite_num=appetite_2;
          }
          if(appetite3.isSelected())
          {
              total= total+appetite_3;
              tag++;
               appetite_num=appetite_3;
          }
          
          if(chill1.isSelected())
          {
              total= total+chill_1;
              tag++;
              chill_num=chill_1;
          }
          if(chill2.isSelected())
          {
              total= total+chill_2;
              tag++;
               chill_num=chill_2;
          }
          if(chill3.isSelected())
          {
              total= total+chill_3;
              tag++;
              chill_num=chill_3;
          }
            
          double value = total/tag;
          result =Double.parseDouble(new DecimalFormat("#.##").format(value));
           // System.out.println(""+result);
      // new_diagnosis diag = new new_diagnosis();
       
         String ids = pa_id.getText();
         String fevers = String.valueOf(fever_num);
         String cough = String.valueOf(cough_num);
         String HR = String.valueOf(HR_num);
         String RR = String.valueOf(RR_num);
         String breathe = String.valueOf(breathe_num);
         String chest = String.valueOf(chest_num);
         String appetite = String.valueOf(appetite_num);
         String results = String.valueOf(result);
         
         if(updateTag == 0)
         {
            String sql = "insert into diagnosis_info(ID,fever,cough,heartbeat,respiratory,breatheing,chest_pain,loss_of_appetite,result) values (?,?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setString(1, ids);
            pst.setString(2, fevers);
            pst.setString(3, cough);
            pst.setString(4, HR);
            pst.setString(5, RR);
            pst.setString(6, breathe);
            pst.setString(7, chest);
            pst.setString(8, appetite);
            pst.setString(9, results);
            pst.execute();
         }
         else if(updateTag == 1)
         {
             String sql6 = "UPDATE diagnosis_info SET fever='" + fevers + "'  ,cough='" + cough + "'  ,heartbeat='" + HR + "'  ,respiratory='" + RR + "'  ,breatheing='" + breathe + "'  ,chest_pain='" + chest + "'  ,loss_of_appetite='" + appetite + "',result='" +results + "' WHERE ID='" + ids + "' ";
             pst = con.prepareStatement(sql6);
             pst.execute();
             updateTag = 0;
         }
          }
           catch (Exception e)
          {
            JOptionPane.showMessageDialog(rootPane, "Database Error");
          }
       
        Results result = new Results();
        Results.result_patient_id.setText(this.pa_id.getText());
     
        result.show();
        
    }//GEN-LAST:event_diagnosisActionPerformed

    
    private void fever1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fever1ActionPerformed

    }//GEN-LAST:event_fever1ActionPerformed

    private void fever2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fever2ActionPerformed
       
    }//GEN-LAST:event_fever2ActionPerformed

    private void fever3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fever3ActionPerformed
       
    }//GEN-LAST:event_fever3ActionPerformed

    private void cough1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cough1ActionPerformed
       
    }//GEN-LAST:event_cough1ActionPerformed

    private void cough2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cough2ActionPerformed
      
    }//GEN-LAST:event_cough2ActionPerformed

    private void cough3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cough3ActionPerformed
        
    }//GEN-LAST:event_cough3ActionPerformed

    private void HR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HR1ActionPerformed
        
    }//GEN-LAST:event_HR1ActionPerformed

    private void HR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HR2ActionPerformed
       
    }//GEN-LAST:event_HR2ActionPerformed

    private void HR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HR3ActionPerformed
       
    }//GEN-LAST:event_HR3ActionPerformed

    private void RR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RR1ActionPerformed
        
    }//GEN-LAST:event_RR1ActionPerformed

    private void RR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RR2ActionPerformed

    }//GEN-LAST:event_RR2ActionPerformed

    private void RR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RR3ActionPerformed
       
    }//GEN-LAST:event_RR3ActionPerformed

    private void Breath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Breath1ActionPerformed
        
    }//GEN-LAST:event_Breath1ActionPerformed

    private void Breathe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Breathe2ActionPerformed
      
    }//GEN-LAST:event_Breathe2ActionPerformed

    private void Breathe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Breathe3ActionPerformed
      
    }//GEN-LAST:event_Breathe3ActionPerformed

    private void Chest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chest1ActionPerformed
     
    }//GEN-LAST:event_Chest1ActionPerformed

    private void Chest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chest2ActionPerformed
        
    }//GEN-LAST:event_Chest2ActionPerformed

    private void Appetite1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Appetite1ActionPerformed

    }//GEN-LAST:event_Appetite1ActionPerformed

    private void Appetite2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Appetite2ActionPerformed
      
    }//GEN-LAST:event_Appetite2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnosis_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnosis_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnosis_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnosis_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnosis_main().setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Appetite1;
    private javax.swing.JRadioButton Appetite2;
    private javax.swing.JRadioButton Breath1;
    private javax.swing.JRadioButton Breathe2;
    private javax.swing.JRadioButton Breathe3;
    private javax.swing.JRadioButton Chest1;
    private javax.swing.JRadioButton Chest2;
    private javax.swing.JRadioButton HR1;
    private javax.swing.JRadioButton HR2;
    private javax.swing.JRadioButton HR3;
    private javax.swing.JRadioButton RR1;
    private javax.swing.JRadioButton RR2;
    private javax.swing.JRadioButton RR3;
    private javax.swing.JRadioButton appetite3;
    private javax.swing.JRadioButton chest3;
    private javax.swing.JRadioButton chill1;
    private javax.swing.JRadioButton chill2;
    private javax.swing.JRadioButton chill3;
    private javax.swing.JRadioButton cough1;
    private javax.swing.JRadioButton cough2;
    private javax.swing.JRadioButton cough3;
    private javax.swing.JButton diagnosis;
    private javax.swing.JRadioButton fever1;
    private javax.swing.JRadioButton fever2;
    private javax.swing.JRadioButton fever3;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    public static javax.swing.JLabel pa_id;
    private javax.swing.JLabel previous_result;
    // End of variables declaration//GEN-END:variables
}
